//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS_WS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public Nullable<int> OID { get; set; }
        public Nullable<int> FID { get; set; }
        public int Qty { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Food Food1 { get; set; }
        public virtual Order Order { get; set; }
        public virtual Order Order1 { get; set; }
    }
}
